# Generated by Django 5.1.1 on 2024-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('isbn', models.CharField(max_length=13)),
                ('language', models.CharField(max_length=30)),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
    ]
